# Generated by Django 3.0.7 on 2020-06-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='basic_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='premium_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='basic',
            name='basic_price',
        ),
        migrations.RemoveField(
            model_name='premium',
            name='premium_price',
        ),
    ]
